/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SubcategoryDetailDto } from '../../models/subcategory-detail-dto';

export interface GetSubcategories$Params {
}

export function getSubcategories(http: HttpClient, rootUrl: string, params?: GetSubcategories$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SubcategoryDetailDto>>> {
  const rb = new RequestBuilder(rootUrl, getSubcategories.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SubcategoryDetailDto>>;
    })
  );
}

getSubcategories.PATH = '/api/v1/subcategories';
