/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface CheckFeaturedOrder$Params {

/**
 * Número de orden a validar
 */
  order: number;
}

export function checkFeaturedOrder(http: HttpClient, rootUrl: string, params: CheckFeaturedOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'occupied'?: boolean;
'order'?: number;
}>> {
  const rb = new RequestBuilder(rootUrl, checkFeaturedOrder.PATH, 'get');
  if (params) {
    rb.path('order', params.order, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'occupied'?: boolean;
      'order'?: number;
      }>;
    })
  );
}

checkFeaturedOrder.PATH = '/api/v1/products/featured-order/{order}';
