/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CashRegisterActionResponse } from '../../models/cash-register-action-response';
import { CreateCashMovementRequest } from '../../models/create-cash-movement-request';

export interface CreateCashMovement$Params {
      body: CreateCashMovementRequest
}

export function createCashMovement(http: HttpClient, rootUrl: string, params: CreateCashMovement$Params, context?: HttpContext): Observable<StrictHttpResponse<CashRegisterActionResponse>> {
  const rb = new RequestBuilder(rootUrl, createCashMovement.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CashRegisterActionResponse>;
    })
  );
}

createCashMovement.PATH = '/api/v1/cash-register/movements';
