/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CashRegisterCutDto } from '../../models/cash-register-cut-dto';

export interface GetCashRegisterHistory$Params {

/**
 * Fecha desde (YYYY-MM-DD)
 */
  desde?: string;

/**
 * Fecha hasta (YYYY-MM-DD)
 */
  hasta?: string;
}

export function getCashRegisterHistory(http: HttpClient, rootUrl: string, params?: GetCashRegisterHistory$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CashRegisterCutDto>>> {
  const rb = new RequestBuilder(rootUrl, getCashRegisterHistory.PATH, 'get');
  if (params) {
    rb.query('desde', params.desde, {});
    rb.query('hasta', params.hasta, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CashRegisterCutDto>>;
    })
  );
}

getCashRegisterHistory.PATH = '/api/v1/cash-register/history';
