/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CashRegisterActionResponse } from '../../models/cash-register-action-response';
import { OpenCashRegisterRequest } from '../../models/open-cash-register-request';

export interface OpenCashRegister$Params {
      body: OpenCashRegisterRequest
}

export function openCashRegister(http: HttpClient, rootUrl: string, params: OpenCashRegister$Params, context?: HttpContext): Observable<StrictHttpResponse<CashRegisterActionResponse>> {
  const rb = new RequestBuilder(rootUrl, openCashRegister.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CashRegisterActionResponse>;
    })
  );
}

openCashRegister.PATH = '/api/v1/cash-register/open';
