/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Estructura estándar de respuesta para operaciones generales
 */
export interface ApiResponse {
  data?: {
} | null;
  message?: string;
  success?: boolean;
}
