/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CashRegisterActionResponse {
  diferencia?: number | null;
  id_corte?: number | null;
  message: string;
  monto_declarado?: number | null;
  monto_esperado?: number | null;
  success: boolean;
}
