/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CashRegisterConfigDto {
  caja_activa: boolean;
  corte_automatico_habilitado: boolean;
  fecha_ultimo_corte?: string | null;
  hora_corte_automatico: string;
  id_corte_actual?: number | null;
  monto_inicial_default: number;
}
