/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CashRegisterTotalsDto {
  monto_esperado: number;
  monto_inicial: number;
  num_egresos: number;
  num_ingresos: number;
  total_egresos: number;
  total_ingresos: number;
}
