/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CashRegisterConfigDto } from '../models/cash-register-config-dto';
import { CashRegisterCutDto } from '../models/cash-register-cut-dto';
import { CashRegisterMovementDto } from '../models/cash-register-movement-dto';
import { CashRegisterTotalsDto } from '../models/cash-register-totals-dto';
export interface CashRegisterStatusDto {
  caja_activa: boolean;
  config: CashRegisterConfigDto;
  corte_actual?: CashRegisterCutDto | null;
  movimientos?: Array<CashRegisterMovementDto>;
  totales?: CashRegisterTotalsDto | null;
}
