/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CashRegisterMovementDto {
  concepto: string;
  fecha_hora: string;
  id: number;
  id_corte: number;
  id_venta?: number | null;
  metodo_pago?: string | null;
  monto: number;
  nombre_usuario?: string | null;
  notas?: string | null;
  referencia?: string | null;
  tipo_movimiento: 'ingreso' | 'egreso' | 'apertura' | 'cierre';
}
