/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CashRegisterCutDto {
  diferencia?: number | null;
  fecha: string;
  hora: string;
  id: number;
  id_usuario?: number | null;
  monto_final?: number | null;
  monto_inicial: number;
  nombre_usuario?: string | null;
  notas?: string | null;
  tipo_movimiento: 'inicio' | 'fin';
  total_egresos?: number | null;
  total_ingresos?: number | null;
}
