/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CategoryResponse {
  id_categoria?: number | null;
  id_subcategoria?: number | null;
  message: string;
  success: boolean;
}
