/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SubcategoryDto } from '../models/subcategory-dto';
export interface CategoryDto {
  id: number;
  nombre: string;
  subcategorias: Array<SubcategoryDto>;
  tiene_imagen?: number;
}
