/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Estructura requerida para registrar un nuevo producto en el catálogo
 */
export interface CreateProductRequest {
  activo?: boolean;
  descripcion: string;
  descuento?: number | null;
  destacado?: boolean;
  id_categoria: number;
  id_subcategoria?: number | null;

  /**
   * Cadena Base64 o URL de la imagen principal
   */
  imagen_principal: string;
  imagen_secundaria_1?: string | null;
  imagen_secundaria_2?: string | null;
  imagen_secundaria_3?: string | null;
  nombre_producto: string;
  orden_destacado?: number | null;
  precio: number;
  sku?: string | null;
  stock: number;

  /**
   * Letra y número de slot (Ej: A1, B2)
   */
  ubicacion: string;
}
