/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateCategoryRequest {
  imagen_categoria?: string | null;
  nombre_categoria: string;
  subcategorias?: Array<string> | null;
}
