/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateCashMovementRequest {
  concepto: string;
  metodo_pago?: string | null;
  monto: number;
  notas?: string | null;
  tipo_movimiento: 'ingreso' | 'egreso';
}
