/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateUserRequest {
  activo?: number | null;
  contrasena: string;
  correo: string;
  nombre: string;
  tipo_usuario?: number | null;
}
