/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChartDto } from '../models/chart-dto';
import { InventoryMetricsDto } from '../models/inventory-metrics-dto';
import { RecentSaleDto } from '../models/recent-sale-dto';
import { SalesMetricsDto } from '../models/sales-metrics-dto';
import { TopProductDto } from '../models/top-product-dto';
export interface DashboardMetricsDto {
  chart: ChartDto;
  inventory: InventoryMetricsDto;
  recentSales: Array<RecentSaleDto>;
  sales: SalesMetricsDto;
  topProducts: Array<TopProductDto>;
}
