/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InventoryMetricsDto {
  productosInactivos: number;
  stockBajo: number;
  stockTotal: number;
  totalProductos: number;
}
