/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserDto } from '../models/user-dto';

/**
 * Respuesta retornada al autenticar credenciales satisfactoriamente
 */
export interface LoginResponse {
  message?: string;
  success?: boolean;
  token?: string | null;
  user?: UserDto;
}
