/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Credenciales requeridas para autenticar al usuario
 */
export interface LoginRequest {

  /**
   * Contraseña de acceso del usuario
   */
  contrasena: string;

  /**
   * Correo electrónico registrado
   */
  correo: string;
}
