/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MovementDetailDto {
  cantidad: number;
  descripcion?: string | null;
  descuento_unitario?: number;
  id_detalle: number;
  id_producto: number;
  iva_unitario?: number;
  nombre_producto: string;
  notas_producto?: string | null;
  precio_unitario: number;
  sku?: string | null;
  subtotal?: number;
  total: number;
}
