/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MovementItemDto {
  descuento_global?: number;
  estatus?: number;
  fecha_venta: string;
  folio: string;
  id_comanda: number;
  id_usuario?: number | null;
  iva?: number;
  metodo_pago: string;
  nombre_usuario?: string | null;
  notas?: string | null;
  subtotal?: number;
  tipo_pago?: number | null;
  tipo_tarjeta?: number | null;
  total: number;
}
