/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MovementsSummaryDto {
  promedioVenta: number;
  totalIngresos: number;
  totalVentas: number;
  ventasHoy: number;
}
