/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductDto {
  activo: number;
  descripcion?: string | null;
  descuento?: number | null;
  destacado?: number;
  id_categoria?: number | null;
  id_producto: number;
  id_subcategoria?: number | null;
  nombre_categoria?: string | null;
  nombre_producto: string;
  nombre_subcategoria?: string | null;
  orden_destacado?: number | null;
  precio: number;
  sku?: string | null;
  stock: number;
  tiene_imagen?: number;
  ubicacion: string;
}
