/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RecentSaleDto {
  fecha_venta?: string;
  folio?: string;
  metodo_pago?: string | null;
  tipo_pago?: string | null;
  total?: number;
}
