/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Datos requeridos para crear una cuenta nueva
 */
export interface RegisterRequest {

  /**
   * Confirmación de la contraseña
   */
  confirmar_contrasena: string;

  /**
   * Contraseña segura (mínimo 6 caracteres)
   */
  contrasena: string;

  /**
   * Correo electrónico del usuario
   */
  correo: string;

  /**
   * Nombre completo del usuario
   */
  nombre: string;
}
