/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SalesMetricsDto {
  fechaLabel: string;
  promedioVenta: number;
  ventasHoyCnt: number;
  ventasHoyMonto: number;
  ventasMesCnt: number;
  ventasMesMonto: number;
}
