/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MovementDetailDto } from '../models/movement-detail-dto';
export interface SaleDetailsResponseDto {
  fecha_venta: string;
  folio: string;
  id_comanda: number;
  metodo_pago?: string;
  notas?: string | null;
  productos: Array<MovementDetailDto>;
  subtotal?: number;
  total: number;
}
