/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SubcategoryDetailDto {
  id_categoria: number;
  id_subcategoria: number;
  imagen_subcategoria?: string | null;
  nombre_categoria: string;
  nombre_subcategoria: string;
}
