/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateCompanyConfigRequest {
  ciudad?: string | null;
  direccion?: string | null;
  email?: string | null;
  estado?: string | null;
  mensaje_ticket?: string | null;
  nombre_empresa: string;
  rfc?: string | null;
  telefono?: string | null;
  website?: string | null;
}
