/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateCashConfigRequest {
  corte_automatico_habilitado: boolean;
  hora_corte_automatico: string;
  monto_inicial_default: number;
}
