/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserItemDto {
  activo: number;
  correo: string;
  fecha_creacion?: string | null;
  id: number;
  nombre: string;
  tipo_usuario: number;
  tipo_usuario_label?: string;
}
