/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Datos del usuario autenticado
 */
export interface UserDto {
  activo?: number;
  correo?: string;
  id?: number;
  nombre?: string;

  /**
   * 1 = Admin, 2 = Empleado/Cajero
   */
  tipo_usuario?: string;
}
