/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CompanyConfigDto } from '../../models/company-config-dto';

export interface GetCompanyConfig$Params {
}

export function getCompanyConfig(http: HttpClient, rootUrl: string, params?: GetCompanyConfig$Params, context?: HttpContext): Observable<StrictHttpResponse<CompanyConfigDto>> {
  const rb = new RequestBuilder(rootUrl, getCompanyConfig.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CompanyConfigDto>;
    })
  );
}

getCompanyConfig.PATH = '/api/v1/config/company';
