/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SaleDetailsResponseDto } from '../../models/sale-details-response-dto';

export interface GetMovementById$Params {

/**
 * ID de la comanda/venta
 */
  id: number;
}

export function getMovementById(http: HttpClient, rootUrl: string, params: GetMovementById$Params, context?: HttpContext): Observable<StrictHttpResponse<SaleDetailsResponseDto>> {
  const rb = new RequestBuilder(rootUrl, getMovementById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SaleDetailsResponseDto>;
    })
  );
}

getMovementById.PATH = '/api/v1/movements/{id}';
