/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MovementsSummaryDto } from '../../models/movements-summary-dto';

export interface GetMovementsSummary$Params {
}

export function getMovementsSummary(http: HttpClient, rootUrl: string, params?: GetMovementsSummary$Params, context?: HttpContext): Observable<StrictHttpResponse<MovementsSummaryDto>> {
  const rb = new RequestBuilder(rootUrl, getMovementsSummary.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MovementsSummaryDto>;
    })
  );
}

getMovementsSummary.PATH = '/api/v1/movements/summary';
