/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MovementItemDto } from '../../models/movement-item-dto';

export interface GetMovements$Params {

/**
 * Fecha inicial (YYYY-MM-DD)
 */
  start_date?: string;

/**
 * Fecha final (YYYY-MM-DD)
 */
  end_date?: string;
}

export function getMovements(http: HttpClient, rootUrl: string, params?: GetMovements$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MovementItemDto>>> {
  const rb = new RequestBuilder(rootUrl, getMovements.PATH, 'get');
  if (params) {
    rb.query('start_date', params.start_date, {});
    rb.query('end_date', params.end_date, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MovementItemDto>>;
    })
  );
}

getMovements.PATH = '/api/v1/movements';
